apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-deployment
  labels:
    app: support
    type: support
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support
  template:
    metadata:
      labels:
        app: support
        type: support
    spec:
      containers:
      - name: support
        image: nginx
        ports:
        - name: support
          containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: support-service
spec:
  selector:
    app: support
    type: support
  type: LoadBalancer
  ports:
    - name: 9443-tcp
      protocol: TCP
      port: 9443
      targetPort: 80
