apiVersion: v1
kind: Service
metadata:
  name: ignition-be-service
spec:
  selector:
    app: ignition
    type: be
  ports:
    - name: 8088-tcp
      protocol: TCP
      port: 8088
      targetPort: 8088
    - name: 8043-tcp
      protocol: TCP
      port: 8043
      targetPort: 8043
    - name: 8060-tcp
      protocol: TCP
      port: 8060
      targetPort: 8060
