apiVersion: v1
kind: Service
metadata:
  name: ignition-fe-service
spec:
  selector:
    app: ignition
    type: fe
  type: LoadBalancer
  ports:
    - name: 8088-tcp
      protocol: TCP
      port: 80
      targetPort: 8088
